[workspace]
resolver="2"
members=[
    "crates/*"
]

[profile.release]
debug=true
lto = "fat"
opt-level = 3
incremental = true

[profile.dev]
lto = "thin"
opt-level = 1
incremental = true

[profile.dev.package."*"]
opt-level = 3