[package]
name = "astro_bench"
version = "0.1.0"
edition = "2021"

[dependencies.astro]
path="../astro"

[dependencies.bevy]
git="https://github.com/bevyengine/bevy.git"
branch="main"
default-features=false